apiVersion: v2
name: cinekube-helm-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cinekube-backend
    version: 0.1.0
    repository: file://../cinekube-backend
    condition: cinekube-backend.enabled
  - name: cinekube-movie-tracker
    version: 0.1.0
    repository: file://../cinekube-movie-tracker
    condition: cinekube-movie-tracker.enabled